module.exports = {
  apps: [
    {
      name: "bin_server",
      cwd: "/home/bin_server_v1",
      script: "src/index.js",
      env: {
        NODE_ENV: "production",
        PORT: 5050,
      },
    },
    {
      name: "bin_server_intestingonly",
      cwd: "/home/bin_server_v1",
      script: "src/index.js",
      env: {
        NODE_ENV: "production",
        PORT: 5051,
        HOST_BD: "127.0.0.1",
        DB_NAME: "bin_admin_db_intestingonly",
        DB_USER: "bin_admin",
        DB_PAS: "ADOlfgitler1945",
        DB_PORT: 5432,
        ADMIN_DB_NAME: "admin_bin_intestingonly",
        ADMIN_DB_USER: "bin_admin",
        ADMIN_DB_PAS: "ADOlfgitler1945",
        ADMIN_DB_HOST: "127.0.0.1",
        ADMIN_DB_PORT: 5432,
        DOMEN: "infokod.com.ua",
        BASE_URL: "https://infokod.com.ua/demo",
        BASE_PROTOCOL: "https",
        FRONTEND_URL: "https://infokod.com.ua/demo",
        ADMIN_API_PREFIX: "/demo/api",
        SUPERADMIN_EMAIL: "admin@infokod.com.ua",
        SUPERADMIN_PASSWORD: "ADOlfgitler1945",
        SUPERADMIN_NAME: "Super Admin",
        ALLOW_SENSITIVE_RESPONSES: "false",
        ADMIN_ALLOW_TOKEN_REVEAL: "false",
        ADMIN_ALLOW_TOKEN_AUTH: "false",
        ADMIN_COOKIE_INSECURE: "false",
      },
    },
    {
      name: "admin_panel",
      cwd: "/home/admin_panel",
      script: "node",
      args: "scripts/serve-dist.js",
      env: {
        NODE_ENV: "production",
        PORT: 4173,
      },
    },
    {
      name: "admin_panel_intestingonly",
      cwd: "/home/admin_panel",
      script: "node",
      args: "scripts/serve-dist.js",
      env: {
        NODE_ENV: "production",
        PORT: 4174,
        DIST_DIR: "/home/admin_panel/dist-intestingonly",
        BASE_PATH: "/demo",
      },
    },
  ],
};
